format_version: 10
pipelines:
  testpipeline:
    group: My-Pipelines
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      testcode:
        git: https://github.com/qiuweiwei111/test.git
        username: chovy.qiu@cxagroup.com
        shallow_clone: false
        auto_update: true
        branch: master
        encrypted_password: AES:Nyvb0FWbbTb2YotbFnwaIQ==:HbqGMS1T1A+fKcH22xgXUg==
    stages:
    - teststage:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          job1:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - hi
                command: echo
                run_if: passed
